name: 'Run checks'

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up node'
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: 'Install node modules'
        run: 'yarn'
      - name: 'Check codestyle'
        run: yarn codestyle
      - name: 'Check linting'
        run: yarn lint
      - name: 'Check circular dependencies'
        run: yarn deps
      - name: 'Check types'
        run: yarn ts
      - name: 'Run tests'
        run: yarn test --ci
      - name: 'Check build'
        run: yarn build
